---
title: "Metas de Redução de Mortes no Trânsito de Municípios Brasileiros"
author: pabsantos
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    navbar:
      - { icon: "fa-github", href: "https://github.com/pabsantos/meta_reducao/", align: left }
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(DT)
library(plotly)
```

```{r data, include=FALSE}
metas <- read_csv("output/municipios_metas.csv")

metas1 <- metas %>% 
  select(codigo, sigla_uf, nome, regiao, porte, media_mortes, var_perc, municipalizacao) %>% 
  rename(meta_porcentagem = var_perc) %>% 
  mutate(meta_porcentagem = round(meta_porcentagem * 100, 2),
         codigo = as.character(codigo),
         media_mortes = round(media_mortes, digits = 1))

metas1 %>% 
  group_by(porte, municipalizacao) %>% 
  summarise(n = n()) %>% 
  pivot_wider(names_from = "municipalizacao", values_from = "n") %>% 
  mutate(Municipalizado = Municipalizado / (Municipalizado + `Não municipalizado`) * 100,
         `Não municipalizado` = 100 - Municipalizado)
```


Column {data-width=600}
-----------------------------------------------------------------------

### Tabela Completa

```{r table}

colunas <- c("Código" = "codigo", "UF" = "sigla_uf", "Nome" = "nome", "Região" = "regiao", "Porte" = "porte", "Média de mortes" = "media_mortes", "Meta (%)" = "meta_porcentagem", "Municipalizado?" = "municipalizacao")

datatable(metas1, rownames = FALSE, colnames = colunas, filter = "top", 
          options = list(scrollY = 700, bPaginate = FALSE))
```

Column {data-width=400}
-----------------------------------------------------------------------

### Distribuição das metas de redução por porte de município

```{r, fig.width=5.5}
p1 <- metas %>% 
  rename(meta_porcentagem = var_perc) %>% 
  ggplot(aes(x = meta_porcentagem, fill=porte)) +
  geom_histogram(binwidth = 0.1, color = "#F1F1F1") +
  scale_fill_brewer(palette = "Set2") +
  scale_x_continuous(breaks = seq(-1, 0, 0.1), minor_breaks = NULL, 
                     labels = seq(-100, 0, 10)) +
  scale_y_continuous(minor_breaks = NULL) +
  facet_wrap(~porte, labeller = labeller(porte = c(
    "Maior porte" = "Maior porte (n = 324)",
    "Médio porte" = "Médio porte (n = 1438)",
    "Menor porte" = "Menor porte (n = 3300)"))) +
  theme_minimal() +
  theme(legend.position = "none") +
  labs(
    x = "Meta de redução (%)",
    y = "Quantidade de municípios")

ggplotly(p1, tooltip = "count")
```

### Meta de redução média por UF

```{r}
p2 <- metas %>% 
  group_by(sigla_uf) %>% 
  summarise(var = sum(var),
            mortes = sum(media_mortes)) %>% 
  mutate(var_perc = var / mortes,
         sigla_uf = fct_reorder(sigla_uf, desc(var_perc))) %>% 
  ggplot(aes(x = sigla_uf, y = -1 * var_perc)) +
  geom_col(fill = "Grey40") +
  geom_text(aes(label = round((var_perc)*100, digits = 0)), color = "white",
            nudge_y = -0.02, size = 2.5) +
  coord_flip() +
  theme_minimal() +
  scale_y_continuous(minor_breaks = NULL, 
                     breaks = seq(0,1,0.1), 
                     limits = c(0,1),
                     labels = seq(0,-100,-10)) +
  labs(y = "Meta de redução (%)", x = "Estado")

ggplotly(p2, tooltip = "")
```

